package com.example.clone.pdm2_project.Model;

/**
 * Created by clone on 17-01-2018.
 */

public class DataResponse {
    public static String fakeResponse = "[\n" +
            "{\"Name\": \"Esparguete, queijo, pimenta e bacalhau\", \"descricao\": \"Numa panela meter a ferver agua com bastante sal. Entretanto numa frigideira com bordas altas saltear as laminas de bacalhau com o azeite e meia concha de agua. Não deixar desfazer muito. Quando a massa estiver cozida al dente saltear na frigideira do bacalhau adicionado a manteiga, uma concha de agua da cozedura, o queijo de ovelha (pecorino) ralado e a pimenta. Envolver com um movimento circular ate formar um creme homogéneo. No final, polvilha-se com pimenta.\"},\n" +
            "{\"Name\": \"Batata recheada de micro-ondas\", \"descricao\": \"Essa é uma das receitas rápidas para o jantar mais simples de serem feitas: cozinhe as batatas até que fiquem macias. Com uma faca, faça um corte horizontal em cada uma e amasse por dentro, dando espaço para o recheio. Coloque os queijos no interior e leve ao micro-ondas em um refratário por dois minutos. Depois, finalize com cebolinha e aproveite.\"},\n" +
            "{\"Name\": \"Sopa de lentilha\", \"descricao\": \"Refogue o bacon com o alho e a cebola até que fique dourado. Coloque os tomates, a pimenta, o cominho e a água e deixe ferver. Em seguida, adicione as lentilhas escorridas e deixe cozinhar por 20 minutos em uma panela tampada até que o legume fique macio. Finalize com sal e sirva.\"},\n" +
            "{\"Name\": \"Polenta de micro-ondas\", \"descricao\": \"Em uma tigela, dissolva o fubá na água fria. Depois, acrescente a manteiga, misture e coloque os demais ingredientes. Cozinhe no micro-ondas por até 12 minutos em potência alta, parando para mexer a cada 5 minutos. Retire com cuidado e delicie-se.\"},\n" +
            "{\"Name\": \"Esparguete, alho, azeite e malagueta\", \"descricao\": \"Pôr a ferver água com sal e cozer o esparguete sem o partir ao meio (há muita gente em Itália que, se vos apanhar a fazer isto, pode deixar de vos falar). Entretanto, limpar as malaguetas das sementes, que normalmente são mais amargas, e cortar em tiras fininhas. Cortar também os dentes de alho a meio em sentido vertical. Fritar em azeite o alho e as malaguetas tendo muito cuidado, não só parque para que o alho não queime mas também porque é preciso retirá-lo do azeite uma vez terminada a sua função de o perfumar (quem gostar muito de alho, deve picá-lo mais fino e deixá-lo ficar). Retirar o esparguete rigorosamente “al dente” e misturar com o azeite. Deixar sempre uma colher ou duas da água da cozedura para misturar melhor. Juntar a salsa e… buono appetito!!\"},\n" +
            "{\"Name\": \"Esparguete, queijo, pimenta e bacalhau\", \"descricao\": \"Numa panela meter a ferver agua com bastante sal. Entretanto numa frigideira com bordas altas saltear as laminas de bacalhau com o azeite e meia concha de agua. Não deixar desfazer muito. Quando a massa estiver cozida al dente saltear na frigideira do bacalhau adicionado a manteiga, uma concha de agua da cozedura, o queijo de ovelha (pecorino) ralado e a pimenta. Envolver com um movimento circular ate formar um creme homogéneo. No final, polvilha-se com pimenta.\"},\n" +
            "{\"Name\": \"Esparguete Carbonara\", \"descricao\": \"Começa-se por cortar o guanciale em tiras com meio centímetro de altura. Depois, as mesmas seguem para uma frigideira com o azeite e o dente de alho esmagado onde ficam a alourar — retira-se o dente de alho e desliga-se o lume assim que o guanciale estiver no ponto. Entretanto, numa tigela, batem-se os ovos com o sal e o queijo pecorino. Numa panela com água a ferver, coze-se o esparguete com uma pitada de sal até ficar al dente. Escorre-se a água da cozedura e põe-se o esparguete na frigideira com o guanciale. Para terminar, falta adicionar a mistura de ovos e queijo, que depois de ser vertida na frigideira, deverá ser bem envolvida com o resto dos ingredientes. Sirva com pimenta preta acabada de moer.\"},\n" +
            "{\"Name\": \"Esparguete à bolonhesa\", \"descricao\": \"Numa panela de barro ou alumínio grosso (com cerca de 20 cm), começa-se por cozinhar o bacon cortado em tiras. Juntam-se três colheres de sopa de azeite (ou 50 gramas de manteiga) e deixa-se a alourar com os vegetais. Concluída esta etapa, entram os 300 gramas de carne moída, que devem ser cozinhados até ganharem um tom castanho brilhante. Junta-se o vinho e mistura-se bem, com cuidado, até o álcool evaporar: só depois é que se pode juntar o tomate, de forma a que cubra o conteúdo do tacho. A partir daí deixa-se a cozinhar em lume brando durante duas horas, mexendo lentamente. Adiciona-se caldo sempre que o nível de líquido baixar demasiado e, quando as duas horas estiverem a chegar ao fim, entra o leite, para cortar a acidez do tomate. Vá provando e ajuste a quantidade de sal e pimenta sempre que achar necessário. Sirva-se do esparguete previamente cozinhado e coloque o molho por cima.\"}\n" +
            "]";
}